networks:
  default:
    external:
      name: roboshop
services:
  # docker run -d --name mongodb --network=roboshop mongodb:1
  mongodb:
    image: mongodb:1
    # networks:
    # - roboshop

  catalogue:
    image: catalogue:1
    # networks:
    # - roboshop
    depends_on:
    - mongodb
  web:
    image: web:v1
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    - shipping
    - payment
  
  redis:
    image: redis
    container_name: redis
    volumes:
    - source: redis
      target: /data
      type: volume

  user:
    image: user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb

  cart:
    image: cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue